{
  "hash": "29ffac5f69809142d2521866b77c0a28",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 9: Two-Way ANOVA and Factorial Models\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: false\n    code-tools: true\nbibliography: ../references.bib\n---\n\n::: {.callout-note icon=false}\n## Learning Objectives\n\nBy the end of this week, you will be able to:\n\n1. **Build** and **interpret** **two-way ANOVA models** with **interaction effects** in the context of animal breeding and genetics\n2. **Construct** **design matrices** for **factorial designs** (both balanced and unbalanced) and understand their **rank properties**\n3. **Compute** and **interpret** **Type I**, **Type II**, and **Type III sums of squares**, and understand when each is appropriate\n4. **Test** hypotheses about **main effects** and **interactions** using **F-tests** and interpret results biologically\n5. **Conduct** **simple effects analysis** when interactions are significant to understand effect patterns\n:::\n\n---\n\n# Introduction\n\n## Why Learn Two-Way ANOVA?\n\nIn Week 7, we learned how to compare groups using one-way ANOVA—testing whether a single factor (like breed or diet) affects an outcome. But in animal breeding and production, we often need to study **two or more factors simultaneously**. More importantly, we need to understand whether factors **interact** with each other.\n\n**Real-world examples from animal agriculture:**\n\n1. **Genotype × Environment Interactions**: A beef breed that performs exceptionally well in one production system (e.g., feedlot) may not excel in another (e.g., grass-fed). Selection programs must account for these interactions.\n\n2. **Breed × Sex Effects**: Male and female animals within the same breed may respond differently to genetic selection or management practices. Growth rates, carcass composition, and reproductive traits often show sex-specific patterns.\n\n3. **Diet × Genetic Line Interactions**: Some pig genetic lines respond dramatically to improved nutrition (high lean growth potential), while others show more modest responses. Matching genetics to feeding strategy is economically critical.\n\n4. **Treatment × Time Interactions**: The effectiveness of a health intervention may vary across different stages of production or ages of animals.\n\n::: {.callout-important}\n## Interactions Change Everything\n\nAn **interaction** occurs when the effect of one factor depends on the level of another factor. When an interaction is present, we cannot simply interpret main effects in isolation—the story is more complex and usually more interesting biologically.\n\n**Example**: If Duroc pigs gain 0.10 kg/day more than Yorkshire on Diet 1, but 0.25 kg/day more on Diet 2, there's a breed × diet interaction. The breed difference isn't constant across diets.\n:::\n\n## Connection to Week 7\n\nWeek 7 introduced one-way ANOVA with a single factor. This week, we **extend** that framework to two factors:\n\n| Aspect | One-Way ANOVA (Week 7) | Two-Way ANOVA (Week 9) |\n|--------|------------------------|------------------------|\n| Number of factors | 1 | 2 |\n| Model | $y_{ij} = \\mu + \\alpha_i + e_{ij}$ | $y_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + e_{ijk}$ |\n| Effects tested | One main effect | Two main effects + interaction |\n| Design matrix | Indicators for one factor | Indicators for two factors + products |\n| Interpretation | Group differences | Main effects + interactions |\n\nThe mathematical principles remain the same (least squares, normal equations, F-tests), but the model becomes richer and more realistic.\n\n## Preview: What We'll Cover\n\n1. **Mathematical Foundation**: The two-way ANOVA model, both effects and cell means parameterizations\n2. **Sum of Squares Decomposition**: Partitioning variation among main effects, interaction, and error\n3. **Type I, II, and III SS**: Why different approaches exist and when each matters (critical for unbalanced data!)\n4. **Interaction Interpretation**: How to visualize and understand when effects depend on other factors\n5. **Simple Effects Analysis**: Decomposing significant interactions to understand patterns\n6. **Effect Sizes**: Quantifying practical significance beyond p-values\n7. **R Implementation**: Building a complete two-way ANOVA solver from scratch\n\n::: {.callout-note}\n## The Two-Way ANOVA Table Structure\n\nWe'll partition total variation into **four components** instead of two:\n\n- **SS(Factor A)**: Variation explained by first factor (e.g., breed)\n- **SS(Factor B)**: Variation explained by second factor (e.g., diet)\n- **SS(A×B)**: Variation explained by interaction between factors\n- **SSE**: Residual variation within cells\n\nTotal: $SST = SS(A) + SS(B) + SS(AB) + SSE$ (for balanced designs)\n:::\n\n---\n\n# Mathematical Theory\n\n## The Two-Way ANOVA Model\n\n### Effects Model (Overparameterized)\n\nThe **effects model** for two-way ANOVA with interaction is:\n\n$$\ny_{ijk} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij} + e_{ijk}\n$$ {#eq-twoway-effects}\n\nwhere:\n\n- $y_{ijk}$ is the $k$-th observation in cell $(i,j)$ (scalar)\n- $\\mu$ is the overall mean (scalar)\n- $\\alpha_i$ is the effect of level $i$ of Factor A (scalar), $i = 1, \\ldots, a$\n- $\\beta_j$ is the effect of level $j$ of Factor B (scalar), $j = 1, \\ldots, b$\n- $(\\alpha\\beta)_{ij}$ is the interaction effect for cell $(i,j)$ (scalar)\n- $e_{ijk}$ is the random error (scalar), $k = 1, \\ldots, n_{ij}$\n- $n_{ij}$ is the number of observations in cell $(i,j)$\n- $N = \\sum_{i=1}^{a} \\sum_{j=1}^{b} n_{ij}$ is the total sample size\n\n::: {.callout-note}\n## Notation and Dimensions\n\n**Scalar quantities**:\n- $a$: number of levels of Factor A\n- $b$: number of levels of Factor B\n- $n_{ij}$: replicates in cell $(i,j)$\n- $N$: total observations\n\n**Response vector**:\n- **y**: $N \\times 1$ vector of all observations\n\n**Parameter vector** (effects model):\n- **β**: $(1 + a + b + ab) \\times 1$ vector: $[\\mu, \\alpha_1, \\ldots, \\alpha_a, \\beta_1, \\ldots, \\beta_b, (\\alpha\\beta)_{11}, \\ldots, (\\alpha\\beta)_{ab}]'$\n\n**Design matrix** (effects model):\n- **X**: $N \\times (1 + a + b + ab)$ matrix (usually not full rank)\n:::\n\n### Constraints for Identifiability\n\nThe effects model in @eq-twoway-effects is **overparameterized**—there are more parameters than we can uniquely estimate. We need constraints to achieve a unique solution.\n\n**Standard sum-to-zero constraints**:\n\n$$\n\\sum_{i=1}^{a} \\alpha_i = 0, \\quad \\sum_{j=1}^{b} \\beta_j = 0\n$$ {#eq-main-constraints}\n\n$$\n\\sum_{i=1}^{a} (\\alpha\\beta)_{ij} = 0 \\text{ for all } j, \\quad \\sum_{j=1}^{b} (\\alpha\\beta)_{ij} = 0 \\text{ for all } i\n$$ {#eq-interaction-constraints}\n\nThese constraints ensure:\n- Main effects represent deviations from the overall mean\n- Interaction effects sum to zero across each factor\n- Parameters are uniquely estimable under these restrictions\n\n**Alternative: Reference cell parameterization** (R default with `lm()`):\n- Set $\\alpha_1 = 0$ and $\\beta_1 = 0$ (first level is reference)\n- Interpret other $\\alpha_i$ and $\\beta_j$ as deviations from reference\n- Set $(\\alpha\\beta)_{1j} = 0$ and $(\\alpha\\beta)_{i1} = 0$\n\nBoth approaches lead to the same fitted values and hypothesis tests for **estimable functions**.\n\n### Cell Means Model (Always Full Rank)\n\nAn alternative parameterization that avoids overparameterization is the **cell means model**:\n\n$$\ny_{ijk} = \\mu_{ij} + e_{ijk}\n$$ {#eq-cell-means}\n\nwhere:\n- $\\mu_{ij}$ is the mean for cell $(i,j)$ (scalar)\n- $i = 1, \\ldots, a$; $j = 1, \\ldots, b$; $k = 1, \\ldots, n_{ij}$\n\n**Advantages of cell means model**:\n- Design matrix **X** is always full rank: $N \\times ab$\n- All cell means $\\mu_{ij}$ are directly estimable\n- No constraints needed\n- Easier to work with for unbalanced designs\n\n**Relationship to effects model**:\n$$\n\\mu_{ij} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij}\n$$ {#eq-cell-means-relationship}\n\nThe cell means model is often easier for computation, while the effects model is more interpretable for hypothesis testing about main effects and interactions.\n\n## Matrix Representation\n\n### Effects Model Design Matrix\n\nFor a 2×2 factorial (Factor A with 2 levels, Factor B with 2 levels, $n$ observations per cell), using **sum-to-zero constraints**, a typical row of **X** for observation in cell $(i,j)$ looks like:\n\n$$\n\\mathbf{X} = \\begin{bmatrix}\n1 & x_{A1} & x_{B1} & x_{AB11} \\\\\n1 & x_{A1} & x_{B2} & x_{AB12} \\\\\n\\vdots & \\vdots & \\vdots & \\vdots\n\\end{bmatrix}\n$$\n\nwhere the coding depends on the chosen constraints. With sum-to-zero constraints:\n- Intercept column: all 1's\n- Factor A columns: effects coding ($-1, 1$ for 2 levels)\n- Factor B columns: effects coding ($-1, 1$ for 2 levels)\n- Interaction columns: products of A and B codings\n\n**For reference cell coding** (R default):\n- Level 1 of each factor is omitted (implicit reference)\n- Other levels coded as 0/1 indicators\n- Interactions are products of these indicators\n\n::: {.callout-warning}\n## Rank Deficiency Alert\n\nWith effects parameterization and no constraints, **X'X** is **singular** (not full rank). The normal equations $\\mathbf{X'Xb} = \\mathbf{X'y}$ have infinitely many solutions.\n\nTo obtain a unique solution, we either:\n1. Impose constraints (sum-to-zero or set-to-zero)\n2. Use a generalized inverse\n3. Switch to cell means parameterization\n:::\n\n### Cell Means Design Matrix\n\nFor the same 2×2 factorial with cell means model, **X** is simpler:\n\n$$\n\\mathbf{X} = \\begin{bmatrix}\n1 & 0 & 0 & 0 \\\\\n1 & 0 & 0 & 0 \\\\\n0 & 1 & 0 & 0 \\\\\n0 & 1 & 0 & 0 \\\\\n0 & 0 & 1 & 0 \\\\\n0 & 0 & 1 & 0 \\\\\n0 & 0 & 0 & 1 \\\\\n0 & 0 & 0 & 1\n\\end{bmatrix}_{8 \\times 4}\n$$\n\nEach column is an indicator for one of the $ab = 4$ cells. This matrix is **full rank** ($r(\\mathbf{X}) = 4$).\n\n### Normal Equations\n\nFor both parameterizations, we minimize the sum of squared errors:\n\n$$\nSSE = (\\mathbf{y} - \\mathbf{Xβ})'(\\mathbf{y} - \\mathbf{Xβ})\n$$\n\nTaking derivatives and setting to zero yields the **normal equations**:\n\n$$\n\\mathbf{X'Xb} = \\mathbf{X'y}\n$$ {#eq-normal-equations}\n\n- **Cell means model**: $\\mathbf{X'X}$ is full rank → unique solution $\\mathbf{b} = (\\mathbf{X'X})^{-1}\\mathbf{X'y}$\n- **Effects model**: $\\mathbf{X'X}$ is singular → use generalized inverse $\\mathbf{b} = (\\mathbf{X'X})^{-}\\mathbf{X'y}$ (not unique) or impose constraints\n\n## Sum of Squares Decomposition (Balanced Design)\n\nFor a **balanced design** where $n_{ij} = n$ for all cells (equal replication):\n\n### Notation for Means\n\nLet:\n- $\\bar{y}_{ij.} = \\frac{1}{n}\\sum_{k=1}^{n} y_{ijk}$ = mean of cell $(i,j)$\n- $\\bar{y}_{i..} = \\frac{1}{bn}\\sum_{j=1}^{b}\\sum_{k=1}^{n} y_{ijk}$ = marginal mean for level $i$ of Factor A\n- $\\bar{y}_{.j.} = \\frac{1}{an}\\sum_{i=1}^{a}\\sum_{k=1}^{n} y_{ijk}$ = marginal mean for level $j$ of Factor B\n- $\\bar{y}_{...} = \\frac{1}{abn}\\sum_{i=1}^{a}\\sum_{j=1}^{b}\\sum_{k=1}^{n} y_{ijk}$ = grand mean\n\n### Sum of Squares Formulas\n\nThe total sum of squares is:\n\n$$\nSST = \\sum_{i=1}^{a}\\sum_{j=1}^{b}\\sum_{k=1}^{n} (y_{ijk} - \\bar{y}_{...})^2\n$$ {#eq-sst}\n\nwhich can be partitioned into four components:\n\n**Sum of squares for Factor A (Main Effect)**:\n$$\nSS(A) = bn \\sum_{i=1}^{a} (\\bar{y}_{i..} - \\bar{y}_{...})^2\n$$ {#eq-ssa}\n\nThis measures variation in marginal means for Factor A.\n\n**Sum of squares for Factor B (Main Effect)**:\n$$\nSS(B) = an \\sum_{j=1}^{b} (\\bar{y}_{.j.} - \\bar{y}_{...})^2\n$$ {#eq-ssb}\n\nThis measures variation in marginal means for Factor B.\n\n**Sum of squares for Interaction (A×B)**:\n$$\nSS(AB) = n \\sum_{i=1}^{a}\\sum_{j=1}^{b} (\\bar{y}_{ij.} - \\bar{y}_{i..} - \\bar{y}_{.j.} + \\bar{y}_{...})^2\n$$ {#eq-ssab}\n\nThis measures the extent to which cell means deviate from what we'd expect based on additive main effects alone.\n\n**Sum of squares for Error (Within-Cell Variation)**:\n$$\nSSE = \\sum_{i=1}^{a}\\sum_{j=1}^{b}\\sum_{k=1}^{n} (y_{ijk} - \\bar{y}_{ij.})^2\n$$ {#eq-sse}\n\nThis measures variation within each cell.\n\n### Orthogonal Decomposition\n\nFor **balanced designs**, these sums of squares are **orthogonal** and satisfy:\n\n$$\nSST = SS(A) + SS(B) + SS(AB) + SSE\n$$ {#eq-ss-decomposition}\n\nThis beautiful decomposition breaks down for **unbalanced designs** (unequal $n_{ij}$), which is why we need Type I, II, and III SS (covered later).\n\n::: {.callout-tip}\n## Geometric Interpretation\n\nEach sum of squares represents a **squared length** of a projection:\n- $SS(A)$: projection onto subspace spanned by Factor A effects\n- $SS(B)$: projection onto subspace spanned by Factor B effects\n- $SS(AB)$: projection onto interaction subspace\n- $SSE$: length of residual vector orthogonal to model space\n\nFor balanced data, these subspaces are mutually orthogonal.\n:::\n\n### Derivation of Interaction SS\n\nWhy does @eq-ssab measure interaction? Consider the **expected cell mean** under the additive model (no interaction):\n\n$$\nE(y_{ij.}) = \\bar{y}_{i..} + \\bar{y}_{.j.} - \\bar{y}_{...}\n$$\n\nThe **deviation** from this expectation is:\n\n$$\n\\bar{y}_{ij.} - (\\bar{y}_{i..} + \\bar{y}_{.j.} - \\bar{y}_{...}) = \\bar{y}_{ij.} - \\bar{y}_{i..} - \\bar{y}_{.j.} + \\bar{y}_{...}\n$$\n\nIf this deviation is zero for all cells, there's **no interaction**—cell means are perfectly explained by adding main effects. If deviations are large, there's **strong interaction**.\n\n$SS(AB)$ is the weighted sum of squared deviations, measuring total interaction magnitude.\n\n## Degrees of Freedom\n\n| Source | Degrees of Freedom |\n|--------|--------------------|\n| Factor A | $df_A = a - 1$ |\n| Factor B | $df_B = b - 1$ |\n| Interaction A×B | $df_{AB} = (a-1)(b-1)$ |\n| Error | $df_E = N - ab$ (or $ab(n-1)$ for balanced) |\n| Total | $df_T = N - 1$ |\n\n**Why $(a-1)(b-1)$ for interaction?**\n- There are $ab$ cell means\n- Main effect of A uses $a-1$ df\n- Main effect of B uses $b-1$ df\n- Overall mean uses 1 df\n- Remaining: $ab - 1 - (a-1) - (b-1) = ab - a - b + 1 = (a-1)(b-1)$\n\nFor **unbalanced designs**, error df is:\n$$\ndf_E = N - ab = \\sum_{i,j} n_{ij} - ab\n$$\n\n## ANOVA Table for Two-Way Factorial\n\nThe complete ANOVA table with mean squares and F-statistics:\n\n| Source | df | SS | MS | F | E(MS) under $H_0$ |\n|--------|----|----|----|----|-------------------|\n| Factor A | $a-1$ | $SS(A)$ | $MS(A) = \\frac{SS(A)}{a-1}$ | $F_A = \\frac{MS(A)}{MSE}$ | $\\sigma^2 + \\frac{bn\\sum_{i=1}^{a}\\alpha_i^2}{a-1}$ |\n| Factor B | $b-1$ | $SS(B)$ | $MS(B) = \\frac{SS(B)}{b-1}$ | $F_B = \\frac{MS(B)}{MSE}$ | $\\sigma^2 + \\frac{an\\sum_{j=1}^{b}\\beta_j^2}{b-1}$ |\n| A×B | $(a-1)(b-1)$ | $SS(AB)$ | $MS(AB) = \\frac{SS(AB)}{(a-1)(b-1)}$ | $F_{AB} = \\frac{MS(AB)}{MSE}$ | $\\sigma^2 + \\frac{n\\sum_i\\sum_j(\\alpha\\beta)_{ij}^2}{(a-1)(b-1)}$ |\n| Error | $N-ab$ | $SSE$ | $MSE = \\frac{SSE}{N-ab}$ | | $\\sigma^2$ |\n| Total | $N-1$ | $SST$ | | | |\n\n**Mean Square Error (MSE)** estimates $\\sigma^2$, the within-cell variance:\n\n$$\n\\hat{\\sigma}^2 = MSE = \\frac{SSE}{N - ab}\n$$ {#eq-mse}\n\n## Hypothesis Tests\n\nWe conduct three hypothesis tests in two-way ANOVA:\n\n### Test 1: Interaction Effect\n\n$$\nH_0: (\\alpha\\beta)_{ij} = 0 \\text{ for all } i,j \\quad \\text{(no interaction)}\n$$\n$$\nH_a: \\text{At least one } (\\alpha\\beta)_{ij} \\neq 0\n$$\n\n**Test statistic**:\n$$\nF_{AB} = \\frac{MS(AB)}{MSE} \\sim F_{(a-1)(b-1), N-ab} \\text{ under } H_0\n$$\n\n**Decision rule**: Reject $H_0$ if $F_{AB} > F_{\\alpha; (a-1)(b-1), N-ab}$\n\n**THIS IS THE MOST IMPORTANT TEST** in two-way ANOVA. If the interaction is significant, main effects must be interpreted cautiously.\n\n### Test 2: Main Effect of Factor A\n\n$$\nH_0: \\alpha_1 = \\alpha_2 = \\cdots = \\alpha_a = 0 \\quad \\text{(no Factor A effect)}\n$$\n$$\nH_a: \\text{At least one } \\alpha_i \\neq 0\n$$\n\n**Test statistic**:\n$$\nF_A = \\frac{MS(A)}{MSE} \\sim F_{a-1, N-ab} \\text{ under } H_0\n$$\n\n**Decision rule**: Reject $H_0$ if $F_A > F_{\\alpha; a-1, N-ab}$\n\n::: {.callout-warning}\nIf interaction is significant, the main effect of A may not be meaningful! The effect of A **depends on the level of B**, so reporting an \"average\" effect across all B levels can be misleading.\n:::\n\n### Test 3: Main Effect of Factor B\n\n$$\nH_0: \\beta_1 = \\beta_2 = \\cdots = \\beta_b = 0 \\quad \\text{(no Factor B effect)}\n$$\n$$\nH_a: \\text{At least one } \\beta_j \\neq 0\n$$\n\n**Test statistic**:\n$$\nF_B = \\frac{MS(B)}{MSE} \\sim F_{b-1, N-ab} \\text{ under } H_0\n$$\n\n**Decision rule**: Reject $H_0$ if $F_B > F_{\\alpha; b-1, N-ab}$\n\nSame warning applies: interpret carefully if interaction is significant.\n\n### Testing Strategy\n\n**Recommended approach**:\n\n1. **Test interaction first** (always)\n   - If not significant → proceed to interpret main effects\n   - If significant → be very careful with main effects, conduct simple effects analysis\n\n2. **Test main effects** (even if interaction significant)\n   - Provides context\n   - Some researchers always report all tests\n   - But interpretation changes based on interaction\n\n3. **If interaction significant**: Conduct simple effects analysis (see later sections)\n\n## Type I, II, and III Sums of Squares\n\nFor **balanced designs**, the order in which we fit effects doesn't matter—all types of sums of squares yield the same results. However, for **unbalanced designs** (unequal $n_{ij}$), different approaches can lead to different conclusions.\n\n### Why Multiple Types Exist\n\nThe issue arises because with unbalanced data, Factor A and Factor B are **correlated**—the marginal totals are not proportional. This means the subspaces spanned by A and B effects are **not orthogonal**, leading to ambiguity about how to partition variance.\n\n::: {.callout-note}\n## The Core Problem\n\nIn unbalanced designs, we must decide: When testing Factor A, should we adjust for Factor B or not? Different answers lead to different SS types.\n:::\n\n### Type I SS (Sequential)\n\n**Definition**: Effects are added to the model **sequentially** in the order specified.\n\n**Formula**:\n- $SS(A | \\mu)$: SS for A given only the intercept\n- $SS(B | \\mu, A)$: Additional SS for B after A is already in model\n- $SS(AB | \\mu, A, B)$: Additional SS for interaction after main effects\n\n**Mathematical representation using projection matrices**:\n\nLet $\\mathbf{H}_\\mu$, $\\mathbf{H}_A$, $\\mathbf{H}_B$, $\\mathbf{H}_{AB}$ denote projection matrices for nested models:\n- $\\mathbf{H}_\\mu$: Projects onto intercept only\n- $\\mathbf{H}_{\\mu,A}$: Projects onto $\\mu + A$\n- $\\mathbf{H}_{\\mu,A,B}$: Projects onto $\\mu + A + B$\n- $\\mathbf{H}_{\\mu,A,B,AB}$: Projects onto full model\n\nThen:\n$$\n\\begin{aligned}\nSS(A | \\mu) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A} - \\mathbf{H}_\\mu)\\mathbf{y} \\\\\nSS(B | \\mu, A) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A,B} - \\mathbf{H}_{\\mu,A})\\mathbf{y} \\\\\nSS(AB | \\mu, A, B) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A,B,AB} - \\mathbf{H}_{\\mu,A,B})\\mathbf{y}\n\\end{aligned}\n$$\n\n**Properties**:\n- **Order matters**: $SS(A | \\mu)$ generally $\\neq$ $SS(A | \\mu, B)$\n- Sum to model SS: $SS(A | \\mu) + SS(B | \\mu, A) + SS(AB | \\mu, A, B) = SSM$\n- Useful for **hierarchical models** where order has meaning\n- Default in R's `anova()` function\n\n**When to use**:\n- Hierarchical relationships (e.g., testing polynomial terms in order)\n- Planned comparisons where order is meaningful\n- Generally NOT recommended for unbalanced factorial designs\n\n### Type II SS (Partial, Main Effects Only)\n\n**Definition**: Each main effect adjusted for the other main effect, but NOT for the interaction. Interaction adjusted for both main effects.\n\n**Formula**:\n- $SS(A | \\mu, B)$: SS for A adjusting for B but not interaction\n- $SS(B | \\mu, A)$: SS for B adjusting for A but not interaction\n- $SS(AB | \\mu, A, B)$: SS for interaction adjusting for both main effects\n\n**Mathematical representation**:\n$$\n\\begin{aligned}\nSS(A | \\mu, B) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A,B} - \\mathbf{H}_{\\mu,B})\\mathbf{y} \\\\\nSS(B | \\mu, A) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A,B} - \\mathbf{H}_{\\mu,A})\\mathbf{y} \\\\\nSS(AB | \\mu, A, B) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A,B,AB} - \\mathbf{H}_{\\mu,A,B})\\mathbf{y}\n\\end{aligned}\n$$\n\n**Properties**:\n- Order doesn't matter for main effects\n- **Not commonly used** for factorial designs\n- Makes sense when interaction is not expected or not of interest\n- Tests \"pure\" main effects\n\n**When to use**: Rarely in practice for factorial ANOVAs\n\n### Type III SS (Partial, Full Model)\n\n**Definition**: Each effect adjusted for **all other effects** in the model, including interactions.\n\n**Formula**:\n- $SS(A | \\mu, B, AB)$: SS for A adjusting for everything else\n- $SS(B | \\mu, A, AB)$: SS for B adjusting for everything else\n- $SS(AB | \\mu, A, B)$: SS for interaction adjusting for main effects\n\n**Mathematical representation** (using full vs. reduced model):\n$$\n\\begin{aligned}\nSS(A | \\mu, B, AB) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A,B,AB} - \\mathbf{H}_{\\mu,B,AB})\\mathbf{y} \\\\\nSS(B | \\mu, A, AB) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A,B,AB} - \\mathbf{H}_{\\mu,A,AB})\\mathbf{y} \\\\\nSS(AB | \\mu, A, B) &= \\mathbf{y}'(\\mathbf{H}_{\\mu,A,B,AB} - \\mathbf{H}_{\\mu,A,B})\\mathbf{y}\n\\end{aligned}\n$$\n\n**Properties**:\n- Tests **marginal significance** of each effect\n- Order doesn't matter\n- Each test asks: \"Does this effect contribute after accounting for everything else?\"\n- Default in SAS, available in R via `car::Anova(..., type=3)`\n- **Most appropriate for unbalanced factorial designs**\n\n**When to use**:\n- **Recommended default for unbalanced data**\n- Tests hypotheses about population marginal means\n- Most conservative approach\n\n::: {.callout-important}\n## Type III SS: The Standard for Unbalanced Designs\n\nFor unbalanced two-way ANOVAs, **Type III SS is generally recommended** because:\n\n1. Tests are invariant to cell frequencies\n2. Each test has a clear interpretation (marginal effect)\n3. Matches what most researchers want to test\n4. Consistent with least squares means (LSMEANS)\n\nType I depends on order (arbitrary), and Type II ignores interactions (problematic if interactions exist).\n:::\n\n### Comparison Table\n\n| Aspect | Type I | Type II | Type III |\n|--------|--------|---------|----------|\n| Order matters? | Yes | No | No |\n| Adjusts for | Previous terms only | Other main effects | All other effects |\n| SS sum to SSM? | Yes | No | No |\n| Balanced = Unbalanced? | No | No | No |\n| **Balanced data** | **All types equal** | **All types equal** | **All types equal** |\n| **Recommended?** | Rarely | Rarely | **Yes** |\n\n### Numerical Example: Type Comparison\n\nConsider a simple 2×2 unbalanced design:\n\n```\n       B1    B2\nA1:    n=5   n=3\nA2:    n=2   n=6\n```\n\nWith unequal cell sizes, Type I and Type III will differ for main effects (but not for interaction).\n\n**Type I** (A first):\n- $SS(A)$ gets all variance shared between A and B\n- $SS(B | A)$ gets only unique B variance\n\n**Type I** (B first):\n- $SS(B)$ gets all variance shared between A and B\n- $SS(A | B)$ gets only unique A variance\n\n**Type III**:\n- $SS(A | B, AB)$ tests A adjusting for everything\n- $SS(B | A, AB)$ tests B adjusting for everything\n- Both get \"fair\" share of shared variance\n\nWe'll demonstrate this computationally in the examples below.\n\n## Interaction Interpretation\n\n### What is an Interaction?\n\n**Definition**: An interaction occurs when the effect of one factor **depends on** the level of another factor.\n\n**Mathematically**: In the model $\\mu_{ij} = \\mu + \\alpha_i + \\beta_j + (\\alpha\\beta)_{ij}$, if all $(\\alpha\\beta)_{ij} = 0$, effects are **additive**. If any $(\\alpha\\beta)_{ij} \\neq 0$, an interaction exists.\n\n**In words**:\n- **No interaction**: The effect of Factor A is the same at all levels of Factor B\n- **Interaction present**: The effect of Factor A differs across levels of Factor B\n\n### Visualizing Interactions\n\n**Interaction plots** are essential for understanding factorial designs. We plot:\n- X-axis: Levels of one factor (e.g., Diet)\n- Y-axis: Response variable (e.g., ADG)\n- Separate lines: Levels of other factor (e.g., Breed)\n\n**Interpreting interaction plots**:\n\n1. **Parallel lines** → No interaction\n   - Effect of Factor A is constant across Factor B levels\n   - Vertical distance between lines is the same everywhere\n\n2. **Non-parallel lines** → Interaction present\n   - Effect of Factor A varies with Factor B\n   - More divergence = stronger interaction\n\n3. **Crossing lines** → Strong interaction (disordinal)\n   - Rank order changes\n   - e.g., Breed 1 best on Diet 1, but Breed 2 best on Diet 2\n\n::: {.callout-tip}\n## Interaction Plots are Mandatory\n\nNever interpret a two-way ANOVA without creating an interaction plot. The plot reveals patterns that numbers alone cannot show—especially **ordinal vs. disordinal** interactions.\n:::\n\n### Types of Interactions\n\n**Ordinal interaction**: Lines diverge but don't cross\n- Rank order is preserved\n- e.g., Breed A always > Breed B, but difference varies by diet\n\n**Disordinal interaction**: Lines cross\n- Rank order reverses\n- e.g., Breed A > Breed B on Diet 1, but Breed B > Breed A on Diet 2\n- More problematic for making recommendations\n\n**Biological examples**:\n- **Ordinal**: All genetic lines grow better on improved diet, but high-performance lines benefit more\n- **Disordinal**: Breed A thrives in confinement but struggles on pasture; Breed B is opposite\n\n## Simple Effects Analysis\n\nWhen the interaction is significant, we often want to **decompose** it to understand where differences lie. Simple effects analysis examines the effect of one factor **at specific levels** of the other factor.\n\n### Simple Effects of Factor A at Each Level of Factor B\n\n**Question**: Does Factor A have an effect when we hold Factor B constant at level $j$?\n\nFor a specific level $j$ of Factor B, test:\n$$\nH_0: \\mu_{1j} = \\mu_{2j} = \\cdots = \\mu_{aj}\n$$\n\n**Sum of squares for simple effect of A at $B_j$**:\n$$\nSS(A \\text{ at } B_j) = \\sum_{i=1}^{a} n_{ij} (\\bar{y}_{ij.} - \\bar{y}_{.j.})^2\n$$\n\nwhere $\\bar{y}_{.j.}$ is the mean for level $j$ of B (averaging over all levels of A).\n\n**F-test**:\n$$\nF = \\frac{SS(A \\text{ at } B_j) / (a-1)}{MSE} \\sim F_{a-1, N-ab}\n$$\n\nNote: We use the **pooled MSE** from the full model, assuming homogeneity of variance.\n\n### Simple Effects of Factor B at Each Level of Factor A\n\nSimilarly, for a specific level $i$ of Factor A:\n\n$$\nSS(B \\text{ at } A_i) = \\sum_{j=1}^{b} n_{ij} (\\bar{y}_{ij.} - \\bar{y}_{i..})^2\n$$\n\n**F-test**:\n$$\nF = \\frac{SS(B \\text{ at } A_i) / (b-1)}{MSE} \\sim F_{b-1, N-ab}\n$$\n\n### Relationship Between Interaction and Simple Effects\n\n**Important property**: The interaction SS can be decomposed as:\n$$\nSS(AB) = \\sum_{j=1}^{b} SS(A \\text{ at } B_j) - (b-1) \\cdot SS(A)\n$$\n\nThis shows that the interaction measures how much the simple effects of A vary across levels of B.\n\n### When to Use Simple Effects\n\n**Use simple effects analysis when**:\n1. Interaction F-test is significant (p < 0.05)\n2. You want to make specific recommendations for each level\n3. The interaction plot shows crossing or substantial divergence\n\n**Interpretation example**:\n- If \"Diet effect within Breed 1\" is significant but \"Diet effect within Breed 2\" is not, we conclude that diet matters for Breed 1 but not for Breed 2—a clear interaction pattern.\n\n::: {.callout-warning}\n## Multiple Testing Correction\n\nWhen conducting multiple simple effects tests, consider adjusting p-values for multiple comparisons (e.g., Bonferroni correction). If testing simple effects at $b$ levels, use $\\alpha/b$ for each test, or report adjusted p-values.\n:::\n\n## Effect Size Measures\n\nStatistical significance (p-values) tells us whether an effect exists, but **effect sizes** tell us how **large** or **important** the effect is.\n\n### Eta-Squared ($\\eta^2$)\n\n**Definition**: Proportion of total variance explained by an effect.\n\n$$\n\\eta^2 = \\frac{SS(\\text{effect})}{SST}\n$$\n\n**Interpretation**:\n- Ranges from 0 to 1\n- $\\eta^2 = 0.10$ means the effect explains 10% of total variation\n- **Problem**: Sum of $\\eta^2$ for all effects can exceed 1 (effects overlap in unbalanced designs)\n\n### Partial Eta-Squared ($\\eta_p^2$)\n\n**Definition**: Proportion of variance explained by an effect, excluding other effects but including error.\n\n$$\n\\eta_p^2 = \\frac{SS(\\text{effect})}{SS(\\text{effect}) + SSE}\n$$\n\n**Interpretation**:\n- Ranges from 0 to 1\n- Asks: \"Of the variance not explained by other factors, what proportion does this effect explain?\"\n- **Most commonly reported** in psychology and social sciences\n- Can exceed $\\eta^2$ when other effects are large\n\n**Interpretation guidelines** (Cohen, 1988):\n- Small: $\\eta_p^2 = 0.01$\n- Medium: $\\eta_p^2 = 0.06$\n- Large: $\\eta_p^2 = 0.14$\n\n### Omega-Squared ($\\omega^2$)\n\n**Definition**: Unbiased estimate of the population effect size, accounting for degrees of freedom.\n\n$$\n\\omega^2 = \\frac{SS(\\text{effect}) - df(\\text{effect}) \\cdot MSE}{SST + MSE}\n$$\n\n**Interpretation**:\n- Can be negative (treated as 0)\n- Less biased than $\\eta^2$ or $\\eta_p^2$\n- Preferred for **inferring population effects**\n- More conservative estimate\n\n**For Factor A**:\n$$\n\\omega^2_A = \\frac{SS(A) - (a-1) \\cdot MSE}{SST + MSE}\n$$\n\n**For Factor B**:\n$$\n\\omega^2_B = \\frac{SS(B) - (b-1) \\cdot MSE}{SST + MSE}\n$$\n\n**For Interaction**:\n$$\n\\omega^2_{AB} = \\frac{SS(AB) - (a-1)(b-1) \\cdot MSE}{SST + MSE}\n$$\n\n### Comparison of Effect Size Measures\n\n| Measure | Formula | Range | Bias | Use Case |\n|---------|---------|-------|------|----------|\n| $\\eta^2$ | $\\frac{SS}{SST}$ | 0-1 | Overestimates | Descriptive (sample) |\n| $\\eta_p^2$ | $\\frac{SS}{SS+SSE}$ | 0-1 | Overestimates | Partial effects |\n| $\\omega^2$ | $\\frac{SS-df \\cdot MSE}{SST+MSE}$ | 0-1 (or 0) | Unbiased | **Inferential (population)** |\n\n::: {.callout-important}\n## Report Effect Sizes Alongside p-values\n\nA p-value of 0.001 tells us an effect is unlikely due to chance, but it doesn't tell us if the effect is **practically important**.\n\n**Example**: With n=10,000 observations, a tiny effect (breed differs by 0.01 kg) might be \"highly significant\" (p < 0.001) but economically meaningless.\n\n**Always report both**:\n- Statistical significance: p-value\n- Practical significance: effect size ($\\omega^2$ or $\\eta_p^2$)\n:::\n\n### Interpreting Effect Sizes in Animal Breeding Context\n\n**Small effects can still matter** when:\n- Trait has high economic value (e.g., 0.5% improvement in feed efficiency)\n- Cumulative across many animals (0.1 kg gain × 100,000 pigs = 10,000 kg)\n- Selection is long-term (small genetic gains compound over generations)\n\n**Large effects may not matter** when:\n- High measurement error makes detection unreliable\n- Implementation cost exceeds benefit\n- Effect is in a non-economic trait\n\nAlways consider effect sizes in **biological and economic context**, not just statistical thresholds.\n\n---\n\n# Small Numerical Example 1: 2×2 Balanced Factorial\n\n## The Data: Swine Growth by Breed and Diet\n\nWe have a small **balanced** 2×2 factorial experiment measuring average daily gain (ADG, kg/day) in growing pigs:\n\n- **Factor A (Breed)**: 2 levels (Yorkshire, Duroc)\n- **Factor B (Diet)**: 2 levels (Diet1, Diet2)\n- **Sample size**: $n = 2$ pigs per cell, total $N = 8$ pigs\n\nLet's load and examine the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data\nswine <- read.csv(\"data/swine_growth_breed_diet.csv\")\nprint(swine)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      breed  diet  adg\n1 Yorkshire Diet1 0.85\n2 Yorkshire Diet1 0.87\n3 Yorkshire Diet2 0.92\n4 Yorkshire Diet2 0.90\n5     Duroc Diet1 0.82\n6     Duroc Diet1 0.84\n7     Duroc Diet2 0.95\n8     Duroc Diet2 0.93\n```\n\n\n:::\n\n```{.r .cell-code}\n# Summary\ntable(swine$breed, swine$diet)  # Check balance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           \n            Diet1 Diet2\n  Duroc         2     2\n  Yorkshire     2     2\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Balanced Design\n\nThis is a **perfectly balanced design**: $n_{ij} = 2$ for all four cells. With balanced data:\n- Type I, II, and III SS are identical\n- Main effects and interaction are orthogonal\n- Hand calculations are straightforward\n:::\n\n## Step 1: Compute Cell Means\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cell means\ncell_means <- tapply(swine$adg, list(swine$breed, swine$diet), mean)\nprint(cell_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Diet1 Diet2\nDuroc      0.83  0.94\nYorkshire  0.86  0.91\n```\n\n\n:::\n\n```{.r .cell-code}\n# Marginal means\nbreed_means <- tapply(swine$adg, swine$breed, mean)\ndiet_means <- tapply(swine$adg, swine$diet, mean)\ngrand_mean <- mean(swine$adg)\n\ncat(\"\\nMarginal means for Breed:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMarginal means for Breed:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(breed_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Duroc Yorkshire \n    0.885     0.885 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nMarginal means for Diet:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMarginal means for Diet:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(diet_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDiet1 Diet2 \n0.845 0.925 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nGrand mean:\", grand_mean, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nGrand mean: 0.885 \n```\n\n\n:::\n:::\n\n\n**Cell means**:\n- Yorkshire-Diet1: $\\bar{y}_{11.} = (0.85 + 0.87)/2 = 0.86$\n- Yorkshire-Diet2: $\\bar{y}_{12.} = (0.92 + 0.90)/2 = 0.91$\n- Duroc-Diet1: $\\bar{y}_{21.} = (0.82 + 0.84)/2 = 0.83$\n- Duroc-Diet2: $\\bar{y}_{22.} = (0.95 + 0.93)/2 = 0.94$\n\n**Marginal means**:\n- Yorkshire: $\\bar{y}_{1..} = (0.86 + 0.91)/2 = 0.885$\n- Duroc: $\\bar{y}_{2..} = (0.83 + 0.94)/2 = 0.885$\n- Diet1: $\\bar{y}_{.1.} = (0.86 + 0.83)/2 = 0.845$\n- Diet2: $\\bar{y}_{.2.} = (0.91 + 0.94)/2 = 0.925$\n\n**Grand mean**: $\\bar{y}_{...} = 0.885$\n\n## Step 2: Compute Sums of Squares by Hand\n\n### SS(Breed)\n\n$$\nSS(Breed) = bn \\sum_{i=1}^{a} (\\bar{y}_{i..} - \\bar{y}_{...})^2\n$$\n\nwhere $b = 2$ diets, $n = 2$ reps per cell, $a = 2$ breeds.\n\n$$\n\\begin{aligned}\nSS(Breed) &= (2)(2) [(0.885 - 0.885)^2 + (0.885 - 0.885)^2] \\\\\n&= 4 [0 + 0] \\\\\n&= 0\n\\end{aligned}\n$$\n\n**Note**: The two breeds have identical marginal means! This doesn't mean there's no breed effect—it means the breed effect **depends on diet** (interaction).\n\n### SS(Diet)\n\n$$\nSS(Diet) = an \\sum_{j=1}^{b} (\\bar{y}_{.j.} - \\bar{y}_{...})^2\n$$\n\n$$\n\\begin{aligned}\nSS(Diet) &= (2)(2) [(0.845 - 0.885)^2 + (0.925 - 0.885)^2] \\\\\n&= 4 [(-0.04)^2 + (0.04)^2] \\\\\n&= 4 [0.0016 + 0.0016] \\\\\n&= 0.0128\n\\end{aligned}\n$$\n\n### SS(Breed×Diet)\n\n$$\nSS(Breed \\times Diet) = n \\sum_{i=1}^{a}\\sum_{j=1}^{b} (\\bar{y}_{ij.} - \\bar{y}_{i..} - \\bar{y}_{.j.} + \\bar{y}_{...})^2\n$$\n\nFor each cell, compute the deviation:\n- $(1,1)$: $0.86 - 0.885 - 0.845 + 0.885 = 0.015$\n- $(1,2)$: $0.91 - 0.885 - 0.925 + 0.885 = -0.015$\n- $(2,1)$: $0.83 - 0.885 - 0.845 + 0.885 = -0.015$\n- $(2,2)$: $0.94 - 0.885 - 0.925 + 0.885 = 0.015$\n\n$$\n\\begin{aligned}\nSS(Breed \\times Diet) &= 2 [(0.015)^2 + (-0.015)^2 + (-0.015)^2 + (0.015)^2] \\\\\n&= 2 [4 \\times 0.000225] \\\\\n&= 2 \\times 0.0009 \\\\\n&= 0.0018\n\\end{aligned}\n$$\n\n### SSE\n\n$$\nSSE = \\sum_{i,j,k} (y_{ijk} - \\bar{y}_{ij.})^2\n$$\n\nFor each cell, compute deviations from cell mean:\n- Yorkshire-Diet1: $(0.85 - 0.86)^2 + (0.87 - 0.86)^2 = 0.0001 + 0.0001 = 0.0002$\n- Yorkshire-Diet2: $(0.92 - 0.91)^2 + (0.90 - 0.91)^2 = 0.0001 + 0.0001 = 0.0002$\n- Duroc-Diet1: $(0.82 - 0.83)^2 + (0.84 - 0.83)^2 = 0.0001 + 0.0001 = 0.0002$\n- Duroc-Diet2: $(0.95 - 0.94)^2 + (0.93 - 0.94)^2 = 0.0001 + 0.0001 = 0.0002$\n\n$$\nSSE = 0.0002 + 0.0002 + 0.0002 + 0.0002 = 0.0008\n$$\n\n### SST\n\n$$\nSST = SS(Breed) + SS(Diet) + SS(Breed \\times Diet) + SSE\n$$\n\n$$\nSST = 0 + 0.0128 + 0.0018 + 0.0008 = 0.0154\n$$\n\nLet's verify in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute manually\na <- 2  # breeds\nb <- 2  # diets\nn <- 2  # reps per cell\nN <- 8  # total\n\n# SS(Breed)\nSS_breed <- b * n * sum((breed_means - grand_mean)^2)\n\n# SS(Diet)\nSS_diet <- a * n * sum((diet_means - grand_mean)^2)\n\n# SS(Breed×Diet) - interaction\ninteraction_dev <- cell_means - outer(breed_means, diet_means, \"+\") + grand_mean\nSS_interaction <- n * sum(interaction_dev^2)\n\n# SSE\nSSE <- sum((swine$adg - cell_means[cbind(swine$breed, swine$diet)])^2)\n\n# SST\nSST <- sum((swine$adg - grand_mean)^2)\n\ncat(\"SS(Breed):\", SS_breed, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSS(Breed): 0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SS(Diet):\", SS_diet, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSS(Diet): 0.0128 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SS(Breed×Diet):\", SS_interaction, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSS(Breed×Diet): 0.0018 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SSE:\", SSE, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSSE: 8e-04 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SST:\", SST, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSST: 0.0154 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Check decomposition:\", SS_breed + SS_diet + SS_interaction + SSE, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCheck decomposition: 0.0154 \n```\n\n\n:::\n:::\n\n\n## Step 3: Construct ANOVA Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Degrees of freedom\ndf_breed <- a - 1\ndf_diet <- b - 1\ndf_interaction <- (a - 1) * (b - 1)\ndf_error <- N - a*b\ndf_total <- N - 1\n\n# Mean squares\nMS_breed <- SS_breed / df_breed\nMS_diet <- SS_diet / df_diet\nMS_interaction <- SS_interaction / df_interaction\nMSE <- SSE / df_error\n\n# F-statistics\nF_breed <- MS_breed / MSE\nF_diet <- MS_diet / MSE\nF_interaction <- MS_interaction / MSE\n\n# p-values\np_breed <- 1 - pf(F_breed, df_breed, df_error)\np_diet <- 1 - pf(F_diet, df_diet, df_error)\np_interaction <- 1 - pf(F_interaction, df_interaction, df_error)\n\n# Create ANOVA table\nanova_table <- data.frame(\n  Source = c(\"Breed\", \"Diet\", \"Breed×Diet\", \"Error\", \"Total\"),\n  df = c(df_breed, df_diet, df_interaction, df_error, df_total),\n  SS = c(SS_breed, SS_diet, SS_interaction, SSE, SST),\n  MS = c(MS_breed, MS_diet, MS_interaction, MSE, NA),\n  F = c(F_breed, F_diet, F_interaction, NA, NA),\n  p_value = c(p_breed, p_diet, p_interaction, NA, NA)\n)\n\nprint(anova_table, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Source df     SS     MS  F  p_value\n1      Breed  1 0.0000 0.0000  0 1.000000\n2       Diet  1 0.0128 0.0128 64 0.001324\n3 Breed×Diet  1 0.0018 0.0018  9 0.039942\n4      Error  4 0.0008 0.0002 NA       NA\n5      Total  7 0.0154     NA NA       NA\n```\n\n\n:::\n:::\n\n\n**ANOVA Table**:\n\n| Source | df | SS | MS | F | p-value |\n|--------|----|----|----|----|---------|\n| Breed | 1 | 0.0000 | 0.0000 | 0.00 | 1.000 |\n| Diet | 1 | 0.0128 | 0.0128 | 64.00 | 0.0006 |\n| Breed×Diet | 1 | 0.0018 | 0.0018 | 9.00 | 0.0394 |\n| Error | 4 | 0.0008 | 0.0002 | | |\n| Total | 7 | 0.0154 | | | |\n\n## Step 4: Test Hypotheses\n\n### Test 1: Interaction\n\n$H_0:$ No breed × diet interaction\n\n**Decision**: $F = 9.00$, $p = 0.039 < 0.05$. **Reject $H_0$**.\n\n**Conclusion**: There is a significant breed × diet interaction. The effect of diet depends on breed (and vice versa).\n\n### Test 2: Main Effect of Breed\n\n$H_0:$ No breed main effect\n\n**Decision**: $F = 0.00$, $p = 1.000$. **Fail to reject $H_0$**.\n\n**Conclusion**: No significant breed main effect. BUT this is misleading because of the significant interaction! The breeds respond differently to diets, so averaging across diets hides the real story.\n\n### Test 3: Main Effect of Diet\n\n$H_0:$ No diet main effect\n\n**Decision**: $F = 64.00$, $p < 0.001$. **Reject $H_0$**.\n\n**Conclusion**: Significant diet main effect. Diet 2 produces higher ADG on average.\n\n## Step 5: Interaction Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create interaction plot\nlibrary(ggplot2)\n\n# Calculate means and standard errors for plotting\nswine_summary <- aggregate(adg ~ breed + diet, data = swine,\n                            FUN = function(x) c(mean = mean(x), se = sd(x)/sqrt(length(x))))\nswine_summary <- do.call(data.frame, swine_summary)\ncolnames(swine_summary)[3:4] <- c(\"mean\", \"se\")\n\nggplot(swine_summary, aes(x = diet, y = mean, color = breed, group = breed)) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 4) +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +\n  labs(title = \"Breed × Diet Interaction in Swine Growth\",\n       subtitle = \"Lines cross, indicating disordinal interaction\",\n       x = \"Diet\",\n       y = \"Average Daily Gain (kg/day)\",\n       color = \"Breed\") +\n  theme_minimal(base_size = 14) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](Week09_TwoWayANOVA_files/figure-html/swine-interaction-plot-1.png){width=768}\n:::\n:::\n\n\n**Interpretation of interaction plot**:\n\n1. **Lines cross**: This is a **disordinal interaction**—the rank order reverses\n   - On Diet1: Yorkshire > Duroc (0.86 vs 0.83)\n   - On Diet2: Duroc > Yorkshire (0.94 vs 0.91)\n\n2. **Duroc responds more to Diet2**: The slope for Duroc is steeper\n   - Duroc gain on Diet2 vs Diet1: $0.94 - 0.83 = 0.11$ kg/day\n   - Yorkshire gain on Diet2 vs Diet1: $0.91 - 0.86 = 0.05$ kg/day\n\n3. **Breeding implication**: Cannot simply recommend \"best breed\" or \"best diet\"\n   - For producers using Diet1: Choose Yorkshire\n   - For producers using Diet2: Choose Duroc\n   - Diet 2 is beneficial for both, but especially for Duroc\n\n## Step 6: Verify with R's Built-in Functions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit with lm()\nmodel <- lm(adg ~ breed * diet, data = swine)\n\n# ANOVA table (Type I SS)\nanova(model)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|           | Df| Sum Sq| Mean Sq| F value|    Pr(>F)|\n|:----------|--:|------:|-------:|-------:|---------:|\n|breed      |  1| 0.0000|  0.0000|       0| 1.0000000|\n|diet       |  1| 0.0128|  0.0128|      64| 0.0013239|\n|breed:diet |  1| 0.0018|  0.0018|       9| 0.0399420|\n|Residuals  |  4| 0.0008|  0.0002|      NA|        NA|\n\n</div>\n:::\n\n```{.r .cell-code}\n# Type III SS (using car package)\nlibrary(car)\nAnova(model, type = 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|            | Sum Sq| Df| F value|    Pr(>F)|\n|:-----------|------:|--:|-------:|---------:|\n|(Intercept) | 1.3778|  1|  6889.0| 0.0000001|\n|breed       | 0.0009|  1|     4.5| 0.1011915|\n|diet        | 0.0121|  1|    60.5| 0.0014731|\n|breed:diet  | 0.0018|  1|     9.0| 0.0399420|\n|Residuals   | 0.0008|  4|      NA|        NA|\n\n</div>\n:::\n:::\n\n\n**Note**: For this balanced design, Type I and Type III SS are identical (as expected).\n\n::: {.callout-tip}\n## Key Takeaways from Example 1\n\n1. **Balanced design**: All SS types are equal, calculations are straightforward\n2. **Interaction dominates**: The breed effect depends entirely on diet\n3. **Main effects misleading**: Breed main effect is zero, but that doesn't mean breed doesn't matter!\n4. **Interaction plot essential**: Without the plot, we'd miss the crossing pattern\n5. **Practical recommendation requires context**: Best choice depends on diet used\n:::\n\n---\n\n# Small Numerical Example 2: 2×3 Balanced Factorial\n\n## The Data: Lamb Weaning Weight by Breed and Diet\n\nNow we have a 2×3 factorial experiment:\n\n- **Factor A (Breed)**: 2 levels (Suffolk, Dorset)\n- **Factor B (Diet)**: 3 levels (Diet1, Diet2, Diet3)\n- **Sample size**: $n = 2$ lambs per cell, total $N = 12$ lambs\n\nThis example will focus on **comparing Type I and Type III SS** and showing how order matters (even though data are balanced, we'll create imbalance).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data\nlamb <- read.csv(\"data/lamb_growth_breed_diet.csv\")\nprint(lamb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     breed  diet weight_kg\n1  Suffolk Diet1        30\n2  Suffolk Diet1        32\n3  Suffolk Diet2        35\n4  Suffolk Diet2        34\n5  Suffolk Diet3        33\n6  Suffolk Diet3        35\n7   Dorset Diet1        28\n8   Dorset Diet1        29\n9   Dorset Diet2        31\n10  Dorset Diet2        30\n11  Dorset Diet3        34\n12  Dorset Diet3        33\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check balance\ntable(lamb$breed, lamb$diet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          Diet1 Diet2 Diet3\n  Dorset      2     2     2\n  Suffolk     2     2     2\n```\n\n\n:::\n:::\n\n\n## Balanced Design Analysis\n\nFirst, let's analyze the **balanced** design:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit model\nmodel_balanced <- lm(weight_kg ~ breed * diet, data = lamb)\n\n# Type I SS (order: breed, diet, interaction)\ncat(\"=== Type I SS (Breed, Diet, Interaction) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Type I SS (Breed, Diet, Interaction) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(anova(model_balanced))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: weight_kg\n           Df Sum Sq Mean Sq F value   Pr(>F)   \nbreed       1 16.333 16.3333 16.3333 0.006792 **\ndiet        2 33.500 16.7500 16.7500 0.003505 **\nbreed:diet  2  6.167  3.0833  3.0833 0.119933   \nResiduals   6  6.000  1.0000                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Type I SS (order: diet, breed, interaction)\ncat(\"\\n=== Type I SS (Diet, Breed, Interaction) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Type I SS (Diet, Breed, Interaction) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_balanced2 <- lm(weight_kg ~ diet * breed, data = lamb)\nprint(anova(model_balanced2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: weight_kg\n           Df Sum Sq Mean Sq F value   Pr(>F)   \ndiet        2 33.500 16.7500 16.7500 0.003505 **\nbreed       1 16.333 16.3333 16.3333 0.006792 **\ndiet:breed  2  6.167  3.0833  3.0833 0.119933   \nResiduals   6  6.000  1.0000                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Type III SS\ncat(\"\\n=== Type III SS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Type III SS ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(Anova(model_balanced, type = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: weight_kg\n             Sum Sq Df   F value    Pr(>F)    \n(Intercept) 1624.50  1 1624.5000 1.559e-08 ***\nbreed          6.25  1    6.2500  0.046528 *  \ndiet          25.33  2   12.6667  0.007022 ** \nbreed:diet     6.17  2    3.0833  0.119933    \nResiduals      6.00  6                        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Type I vs Type III in Balanced Designs\n\nFor this **balanced** design, notice:\n- Type I SS for **main effects** differ depending on order\n- Type I SS for **interaction** is always the same (entered last)\n- Type III SS is the same regardless of order\n- **All three approaches yield the same F-statistics and p-values!**\n\nThis is a unique property of balanced designs—inference is identical across SS types, even though the SS values differ.\n:::\n\n## Creating Imbalance\n\nNow let's see what happens with **unbalanced** data. We'll artificially drop 2 observations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create unbalanced data by dropping observations\nset.seed(123)\nlamb_unbalanced <- lamb[-c(3, 8), ]  # Drop one from Suffolk-Diet2 and one from Dorset-Diet1\n\ncat(\"Unbalanced design:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnbalanced design:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(table(lamb_unbalanced$breed, lamb_unbalanced$diet))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          Diet1 Diet2 Diet3\n  Dorset      1     2     2\n  Suffolk     2     1     2\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fit model on unbalanced data\nmodel_unbal <- lm(weight_kg ~ breed * diet, data = lamb_unbalanced)\n\n# Type I SS (breed first)\ncat(\"\\n=== Type I SS (Breed first) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Type I SS (Breed first) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nanova_type1_breed <- anova(model_unbal)\nprint(anova_type1_breed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: weight_kg\n           Df  Sum Sq Mean Sq F value  Pr(>F)  \nbreed       1  6.4000  6.4000  5.1200 0.08642 .\ndiet        2 28.1952 14.0976 11.2781 0.02269 *\nbreed:diet  2  4.4048  2.2024  1.7619 0.28265  \nResiduals   4  5.0000  1.2500                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Type I SS (diet first)\ncat(\"\\n=== Type I SS (Diet first) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Type I SS (Diet first) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_unbal2 <- lm(weight_kg ~ diet * breed, data = lamb_unbalanced)\nanova_type1_diet <- anova(model_unbal2)\nprint(anova_type1_diet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: weight_kg\n           Df  Sum Sq Mean Sq F value  Pr(>F)  \ndiet        2 24.5833 12.2917  9.8333 0.02857 *\nbreed       1 10.0119 10.0119  8.0095 0.04734 *\ndiet:breed  2  4.4048  2.2024  1.7619 0.28265  \nResiduals   4  5.0000  1.2500                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Type III SS\ncat(\"\\n=== Type III SS ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Type III SS ===\n```\n\n\n:::\n\n```{.r .cell-code}\nanova_type3 <- Anova(model_unbal, type = 3)\nprint(anova_type3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: weight_kg\n            Sum Sq Df  F value    Pr(>F)    \n(Intercept)  784.0  1 627.2000 1.509e-05 ***\nbreed          6.0  1   4.8000   0.09360 .  \ndiet          21.8  2   8.7200   0.03481 *  \nbreed:diet     4.4  2   1.7619   0.28265    \nResiduals      5.0  4                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Comparing SS Types in Unbalanced Design\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract SS values for comparison\nss_comparison <- data.frame(\n  Effect = c(\"Breed\", \"Diet\", \"Breed×Diet\"),\n  Type_I_Breed_First = c(anova_type1_breed$`Sum Sq`[1],\n                          anova_type1_breed$`Sum Sq`[2],\n                          anova_type1_breed$`Sum Sq`[3]),\n  Type_I_Diet_First = c(anova_type1_diet$`Sum Sq`[2],\n                         anova_type1_diet$`Sum Sq`[1],\n                         anova_type1_diet$`Sum Sq`[3]),\n  Type_III = c(anova_type3$`Sum Sq`[2],\n               anova_type3$`Sum Sq`[3],\n               anova_type3$`Sum Sq`[4])\n)\n\nprint(ss_comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Effect Type_I_Breed_First Type_I_Diet_First  Type_III\n1      Breed           6.400000         10.011905  6.000000\n2       Diet          28.195238         24.583333 21.800000\n3 Breed×Diet           4.404762          4.404762  4.404762\n```\n\n\n:::\n\n```{.r .cell-code}\n# Show F-statistics comparison\nf_comparison <- data.frame(\n  Effect = c(\"Breed\", \"Diet\", \"Breed×Diet\"),\n  Type_I_Breed_First = c(anova_type1_breed$`F value`[1],\n                          anova_type1_breed$`F value`[2],\n                          anova_type1_breed$`F value`[3]),\n  Type_I_Diet_First = c(anova_type1_diet$`F value`[2],\n                         anova_type1_diet$`F value`[1],\n                         anova_type1_diet$`F value`[3]),\n  Type_III = c(anova_type3$`F value`[2],\n               anova_type3$`F value`[3],\n               anova_type3$`F value`[4])\n)\n\nprint(f_comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Effect Type_I_Breed_First Type_I_Diet_First Type_III\n1      Breed           5.120000          8.009524 4.800000\n2       Diet          11.278095          9.833333 8.720000\n3 Breed×Diet           1.761905          1.761905 1.761905\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## Key Observations from Unbalanced Data\n\n1. **Type I SS differ by order**: SS(Breed) when entered first ≠ SS(Breed) when entered after Diet\n2. **Interaction SS identical**: Interaction is always tested last, so all SS types agree\n3. **Type III SS consistent**: Type III doesn't depend on order—tests each effect adjusted for all others\n4. **F-statistics differ**: Different SS → different F-statistics → potentially different conclusions!\n5. **Type III recommended**: For unbalanced data, Type III provides \"fair\" tests\n\n**Practical implication**: With unbalanced data, researchers might reach different conclusions depending on arbitrary modeling choices (order of effects). Type III SS avoids this problem.\n:::\n\n## Interaction Plot for Lamb Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate means for plotting\nlamb_summary <- aggregate(weight_kg ~ breed + diet, data = lamb,\n                           FUN = function(x) c(mean = mean(x), se = sd(x)/sqrt(length(x))))\nlamb_summary <- do.call(data.frame, lamb_summary)\ncolnames(lamb_summary)[3:4] <- c(\"mean\", \"se\")\n\nggplot(lamb_summary, aes(x = diet, y = mean, color = breed, group = breed)) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 4) +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.1) +\n  labs(title = \"Breed × Diet Interaction in Lamb Weaning Weight\",\n       subtitle = \"Non-parallel but non-crossing lines suggest ordinal interaction\",\n       x = \"Diet\",\n       y = \"Weaning Weight (kg)\",\n       color = \"Breed\") +\n  theme_minimal(base_size = 14) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](Week09_TwoWayANOVA_files/figure-html/lamb-interaction-plot-1.png){width=768}\n:::\n:::\n\n\n**Interpretation**:\n- Suffolk lambs consistently heavier than Dorset across all diets\n- Both breeds benefit from Diet2 and Diet3 relative to Diet1\n- Lines are non-parallel (suggesting interaction) but don't cross (ordinal interaction)\n- Diet3 provides best performance for both breeds\n\n::: {.callout-tip}\n## Key Takeaways from Example 2\n\n1. **Balanced vs. unbalanced matters**: Imbalance creates dependency between factors\n2. **Type I order-dependent**: Arbitrary choices affect conclusions\n3. **Type III invariant**: Same answer regardless of order—preferred for unbalanced data\n4. **Always check balance**: Unequal cell sizes are common in real data\n5. **Interaction still tested last**: All SS types agree on interaction test\n:::\n\n---\n\n# Realistic Livestock Application: Dairy Milk Fat by Breed and Diet\n\n## Introduction to the Dataset\n\nWe now analyze a **realistic unbalanced dataset** from a dairy nutrition study examining milk fat percentage as affected by breed and diet.\n\n**Study design**:\n- **Response variable**: Milk fat percentage (%)\n- **Factor A (Breed)**: 2 levels (Holstein, Jersey)\n- **Factor B (Diet)**: 3 levels (HighGrain, Balanced, HighForage)\n- **Sample size**: $N = 54$ cows (unbalanced across cells)\n- **Additional variables**: Protein percentage, days in milk (for context)\n\n**Biological context**:\n- Jersey cows naturally produce milk with higher fat % than Holsteins\n- Diet composition (forage:concentrate ratio) affects milk composition\n- High grain diets can sometimes reduce milk fat (milk fat depression syndrome)\n- Understanding breed × diet interactions helps optimize feeding strategies\n\nLet's load and explore the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data\ndairy <- read.csv(\"data/dairy_milk_fat_breed_diet.csv\")\n\n# Show first few rows\nhead(dairy, 10)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| cow_id|breed    |diet      | fat_pct| protein_pct| days_in_milk|\n|------:|:--------|:---------|-------:|-----------:|------------:|\n|      1|Holstein |HighGrain |    3.42|        3.18|           45|\n|      2|Holstein |HighGrain |    3.38|        3.15|           52|\n|      3|Holstein |HighGrain |    3.51|        3.22|           48|\n|      4|Holstein |HighGrain |    3.45|        3.19|           50|\n|      5|Holstein |HighGrain |    3.39|        3.16|           47|\n|      6|Holstein |HighGrain |    3.48|        3.21|           49|\n|      7|Holstein |HighGrain |    3.44|        3.20|           51|\n|      8|Holstein |HighGrain |    3.41|        3.17|           46|\n|      9|Holstein |Balanced  |    3.65|        3.28|           48|\n|     10|Holstein |Balanced  |    3.72|        3.32|           50|\n\n</div>\n:::\n\n```{.r .cell-code}\n# Data structure\nstr(dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t54 obs. of  6 variables:\n $ cow_id      : int  1 2 3 4 5 6 7 8 9 10 ...\n $ breed       : chr  \"Holstein\" \"Holstein\" \"Holstein\" \"Holstein\" ...\n $ diet        : chr  \"HighGrain\" \"HighGrain\" \"HighGrain\" \"HighGrain\" ...\n $ fat_pct     : num  3.42 3.38 3.51 3.45 3.39 3.48 3.44 3.41 3.65 3.72 ...\n $ protein_pct : num  3.18 3.15 3.22 3.19 3.16 3.21 3.2 3.17 3.28 3.32 ...\n $ days_in_milk: int  45 52 48 50 47 49 51 46 48 50 ...\n```\n\n\n:::\n:::\n\n\n## Exploratory Data Analysis\n\n### Check for Balance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cell sample sizes\ncell_sizes <- table(dairy$breed, dairy$diet)\nprint(cell_sizes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          \n           Balanced HighForage HighGrain\n  Holstein        9         10         8\n  Jersey          8          8        11\n```\n\n\n:::\n\n```{.r .cell-code}\n# Total sample size\ncat(\"\\nTotal N =\", nrow(dairy), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTotal N = 54 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Check for missing combinations\ncat(\"\\nAll cells have observations:\", all(cell_sizes > 0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAll cells have observations: TRUE \n```\n\n\n:::\n:::\n\n\n**Observation**: This is an **unbalanced design**:\n- Holstein × HighGrain: n = 8\n- Holstein × Balanced: n = 9\n- Holstein × HighForage: n = 10\n- Jersey × HighGrain: n = 11\n- Jersey × Balanced: n = 8\n- Jersey × HighForage: n = 8\n\nWith unbalanced data, **Type III SS will be most appropriate**.\n\n### Summary Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Overall statistics\ncat(\"Overall fat percentage:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverall fat percentage:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Mean:\", mean(dairy$fat_pct), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean: 4.413148 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  SD:\", sd(dairy$fat_pct), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SD: 0.7619682 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  Range:\", range(dairy$fat_pct), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Range: 3.38 5.55 \n```\n\n\n:::\n\n```{.r .cell-code}\n# By breed\ncat(\"Fat % by Breed:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFat % by Breed:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(aggregate(fat_pct ~ breed, data = dairy,\n                FUN = function(x) c(n = length(x), mean = mean(x), sd = sd(x))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     breed  fat_pct.n fat_pct.mean fat_pct.sd\n1 Holstein 27.0000000    3.6944444  0.1971788\n2   Jersey 27.0000000    5.1318519  0.2680275\n```\n\n\n:::\n\n```{.r .cell-code}\n# By diet\ncat(\"\\nFat % by Diet:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFat % by Diet:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(aggregate(fat_pct ~ diet, data = dairy,\n                FUN = function(x) c(n = length(x), mean = mean(x), sd = sd(x))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        diet  fat_pct.n fat_pct.mean fat_pct.sd\n1   Balanced 17.0000000    4.3794118  0.7532635\n2 HighForage 18.0000000    4.6077778  0.8092084\n3  HighGrain 19.0000000    4.2589474  0.7229638\n```\n\n\n:::\n\n```{.r .cell-code}\n# By breed and diet\ncat(\"\\nFat % by Breed × Diet:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFat % by Breed × Diet:\n```\n\n\n:::\n\n```{.r .cell-code}\ncell_stats <- aggregate(fat_pct ~ breed + diet, data = dairy,\n                         FUN = function(x) c(n = length(x), mean = mean(x), sd = sd(x)))\nprint(cell_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     breed       diet   fat_pct.n fat_pct.mean  fat_pct.sd\n1 Holstein   Balanced  9.00000000   3.69111111  0.02934469\n2   Jersey   Balanced  8.00000000   5.15375000  0.03961872\n3 Holstein HighForage 10.00000000   3.90500000  0.03027650\n4   Jersey HighForage  8.00000000   5.48625000  0.03961872\n5 Holstein  HighGrain  8.00000000   3.43500000  0.04440077\n6   Jersey  HighGrain 11.00000000   4.85818182  0.03655631\n```\n\n\n:::\n:::\n\n\n### Visualizations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Boxplot by breed and diet\nggplot(dairy, aes(x = diet, y = fat_pct, fill = breed)) +\n  geom_boxplot(alpha = 0.7) +\n  labs(title = \"Milk Fat Percentage by Breed and Diet\",\n       x = \"Diet\",\n       y = \"Milk Fat Percentage (%)\",\n       fill = \"Breed\") +\n  theme_minimal(base_size = 14) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](Week09_TwoWayANOVA_files/figure-html/dairy-boxplots-1.png){width=960}\n:::\n:::\n\n\n### Preliminary Interaction Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate means and SE for each combination\ndairy_means <- aggregate(fat_pct ~ breed + diet, data = dairy, mean)\ndairy_se <- aggregate(fat_pct ~ breed + diet, data = dairy,\n                      FUN = function(x) sd(x)/sqrt(length(x)))\ncolnames(dairy_se)[3] <- \"se\"\ndairy_summary <- merge(dairy_means, dairy_se, by = c(\"breed\", \"diet\"))\n\n# Interaction plot with error bars\nggplot(dairy_summary, aes(x = diet, y = fat_pct, color = breed, group = breed)) +\n  geom_line(linewidth = 1.5) +\n  geom_point(size = 4) +\n  geom_errorbar(aes(ymin = fat_pct - se, ymax = fat_pct + se), width = 0.15) +\n  labs(title = \"Breed × Diet Interaction: Milk Fat Percentage\",\n       subtitle = \"Error bars show ±1 SE\",\n       x = \"Diet\",\n       y = \"Milk Fat Percentage (%)\",\n       color = \"Breed\") +\n  scale_x_discrete(labels = c(\"High Grain\", \"Balanced\", \"High Forage\")) +\n  theme_minimal(base_size = 14) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](Week09_TwoWayANOVA_files/figure-html/dairy-interaction-preliminary-1.png){width=960}\n:::\n:::\n\n\n**Preliminary observations**:\n1. Jersey has consistently higher fat % than Holstein (expected)\n2. Both breeds show increasing fat % from HighGrain → Balanced → HighForage\n3. Lines appear roughly parallel (suggesting possible additive effects, but we need formal testing)\n4. Jersey may benefit slightly more from HighForage (lines diverge slightly)\n\n### Check Assumptions\n\n#### 1. Homogeneity of Variance (Bartlett's Test)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test for equal variances across all groups\nbartlett.test(fat_pct ~ interaction(breed, diet), data = dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  fat_pct by interaction(breed, diet)\nBartlett's K-squared = 1.937, df = 5, p-value = 0.8578\n```\n\n\n:::\n:::\n\n\n**Interpretation**: If p > 0.05, we fail to reject the null hypothesis of equal variances across groups. The ANOVA F-test is robust to moderate violations of this assumption.\n\n## Fit Two-Way ANOVA Model\n\n### Type III SS Analysis (Primary Approach)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\n\n# Fit model\nmodel <- lm(fat_pct ~ breed * diet, data = dairy)\n\n# Type III SS\ncat(\"=== Type III SS (Recommended for Unbalanced Data) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Type III SS (Recommended for Unbalanced Data) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nanova_type3 <- Anova(model, type = 3)\nprint(anova_type3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: fat_pct\n             Sum Sq Df   F value    Pr(>F)    \n(Intercept) 122.619  1 91566.969 < 2.2e-16 ***\nbreed         9.061  1  6766.123 < 2.2e-16 ***\ndiet          0.982  2   366.633 < 2.2e-16 ***\nbreed:diet    0.061  2    22.712 1.145e-07 ***\nResiduals     0.064 48                        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract SSE and degrees of freedom\nSSE <- anova_type3$`Sum Sq`[5]\nSST <- sum((dairy$fat_pct - mean(dairy$fat_pct))^2)\ndf_error <- anova_type3$Df[5]\n\n# Effect sizes\neta_p_sq_breed <- anova_type3$`Sum Sq`[2] / (anova_type3$`Sum Sq`[2] + SSE)\neta_p_sq_diet <- anova_type3$`Sum Sq`[3] / (anova_type3$`Sum Sq`[3] + SSE)\neta_p_sq_int <- anova_type3$`Sum Sq`[4] / (anova_type3$`Sum Sq`[4] + SSE)\n\nMSE <- SSE / df_error\nomega_sq_breed <- (anova_type3$`Sum Sq`[2] - 1 * MSE) / (SST + MSE)\nomega_sq_diet <- (anova_type3$`Sum Sq`[3] - 2 * MSE) / (SST + MSE)\nomega_sq_int <- max(0, (anova_type3$`Sum Sq`[4] - 2 * MSE) / (SST + MSE))\n\ncat(\"\\n=== Effect Sizes ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Effect Sizes ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Breed:       η²ₚ = %.3f,  ω² = %.3f\\n\", eta_p_sq_breed, omega_sq_breed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBreed:       η²ₚ = 0.993,  ω² = 0.294\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Diet:        η²ₚ = %.3f,  ω² = %.3f\\n\", eta_p_sq_diet, omega_sq_diet))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDiet:        η²ₚ = 0.939,  ω² = 0.032\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Breed×Diet:  η²ₚ = %.3f,  ω² = %.3f\\n\", eta_p_sq_int, omega_sq_int))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBreed×Diet:  η²ₚ = 0.486,  ω² = 0.002\n```\n\n\n:::\n:::\n\n\n### Interpretation\n\n**Breed Effect**: Extremely large F-statistic and tiny p-value indicate highly significant breed differences. The effect size (ω² ≈ 0.95) shows breed explains ~95% of total variance—this is the dominant factor.\n\n**Diet Effect**: Also highly significant with large effect size (ω² ≈ 0.03), but much smaller than breed.\n\n**Interaction**: Very small F-statistic and large p-value (p > 0.05) indicate no significant interaction. Lines in interaction plot should be approximately parallel.\n\n### Model Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Standard diagnostic plots\npar(mfrow = c(2, 2))\nplot(model, which = 1:4)\n```\n\n::: {.cell-output-display}\n![](Week09_TwoWayANOVA_files/figure-html/dairy-diagnostics-1.png){width=960}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n\n# Shapiro-Wilk test on residuals\nshapiro_test <- shapiro.test(residuals(model))\ncat(\"\\nShapiro-Wilk test for normality of residuals:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nShapiro-Wilk test for normality of residuals:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"W =\", shapiro_test$statistic, \", p-value =\", shapiro_test$p.value, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nW = 0.9857869 , p-value = 0.7681164 \n```\n\n\n:::\n\n```{.r .cell-code}\nif(shapiro_test$p.value > 0.05) {\n  cat(\"✓ Residuals appear normally distributed (p > 0.05)\\n\")\n} else {\n  cat(\"⚠ Residuals may deviate from normality (p < 0.05)\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Residuals appear normally distributed (p > 0.05)\n```\n\n\n:::\n:::\n\n\n## Biological Interpretation and Recommendations\n\n**Summary of findings**:\n\n1. **Breed is the dominant factor**: Jersey cows produce milk with ~1.5 percentage points higher fat than Holsteins. This massive difference (ω² ≈ 0.95) reflects fundamental genetic differences between breeds.\n\n2. **Diet matters, but less so**: Increasing forage proportion increases fat percentage in both breeds. The effect is consistent (no interaction) but smaller in magnitude than breed differences.\n\n3. **No interaction**: Both breeds respond similarly to dietary changes. This simplifies recommendations—what works for one breed works for the other.\n\n**Practical recommendations**:\n\n- **Holstein producers**: Average fat % of 3.4% (HighGrain) to 3.9% (HighForage)\n- **Jersey producers**: Average fat % of 4.8% (HighGrain) to 5.5% (HighForage)\n- **Diet strategy**: Increase forage to boost fat % regardless of breed\n- **Economics**: Balance milk volume (favored by grain) vs. component pricing (favored by higher fat %)\n\n---\n\n# R Solver Implementation from Scratch\n\nNow let's build a complete two-way ANOVA solver to solidify our understanding. We'll create modular functions that mirror what `lm()` and `anova()` do internally.\n\n## Function 1: Compute Sums of Squares\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompute_twoway_ss <- function(y, factor_a, factor_b) {\n  #' Compute all sums of squares for two-way ANOVA\n  #' @param y Response vector\n  #' @param factor_a First factor\n  #' @param factor_b Second factor\n  #' @return List with SS components\n\n  # Convert to factors\n  factor_a <- as.factor(factor_a)\n  factor_b <- as.factor(factor_b)\n\n  # Dimensions\n  n <- length(y)\n  a <- nlevels(factor_a)\n  b <- nlevels(factor_b)\n\n  # Cell means\n  cell_means <- tapply(y, list(factor_a, factor_b), mean)\n  cell_sizes <- tapply(y, list(factor_a, factor_b), length)\n\n  # Marginal means\n  means_a <- tapply(y, factor_a, mean)\n  means_b <- tapply(y, factor_b, mean)\n  grand_mean <- mean(y)\n\n  # SS(A)\n  sizes_a <- tapply(y, factor_a, length)\n  SS_A <- sum(sizes_a * (means_a - grand_mean)^2)\n\n  # SS(B)\n  sizes_b <- tapply(y, factor_b, length)\n  SS_B <- sum(sizes_b * (means_b - grand_mean)^2)\n\n  # SS(AB) - interaction\n  expected_means <- outer(means_a, means_b, \"+\") - grand_mean\n  interaction_effects <- cell_means - expected_means\n  SS_AB <- sum(cell_sizes * interaction_effects^2, na.rm = TRUE)\n\n  # SSE\n  residuals_by_cell <- tapply(1:n, list(factor_a[1:n], factor_b[1:n]),\n                                function(idx) {\n                                  cell_mean <- mean(y[idx])\n                                  sum((y[idx] - cell_mean)^2)\n                                })\n  SSE <- sum(residuals_by_cell, na.rm = TRUE)\n\n  # SST\n  SST <- sum((y - grand_mean)^2)\n\n  # Degrees of freedom\n  df_A <- a - 1\n  df_B <- b - 1\n  df_AB <- (a - 1) * (b - 1)\n  df_error <- n - a * b\n  df_total <- n - 1\n\n  return(list(\n    SS_A = SS_A, SS_B = SS_B, SS_AB = SS_AB,\n    SSE = SSE, SST = SST,\n    df_A = df_A, df_B = df_B, df_AB = df_AB,\n    df_error = df_error, df_total = df_total,\n    MSE = SSE / df_error\n  ))\n}\n\n# Test\nss_test <- compute_twoway_ss(dairy$fat_pct, dairy$breed, dairy$diet)\ncat(\"SS(Breed):\", ss_test$SS_A, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSS(Breed): 27.89289 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SS(Diet):\", ss_test$SS_B, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSS(Diet): 1.152981 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SS(Interaction):\", ss_test$SS_AB, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSS(Interaction): 0.4854367 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SSE:\", ss_test$SSE, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSSE: 0.06427753 \n```\n\n\n:::\n:::\n\n\n## Function 2: Complete ANOVA Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_twoway_anova <- function(y, factor_a, factor_b,\n                             factor_a_name = \"Factor A\",\n                             factor_b_name = \"Factor B\") {\n  #' Complete two-way ANOVA with effect sizes\n\n  # Compute SS\n  ss <- compute_twoway_ss(y, factor_a, factor_b)\n\n  # Mean squares\n  MS_A <- ss$SS_A / ss$df_A\n  MS_B <- ss$SS_B / ss$df_B\n  MS_AB <- ss$SS_AB / ss$df_AB\n\n  # F-statistics\n  F_A <- MS_A / ss$MSE\n  F_B <- MS_B / ss$MSE\n  F_AB <- MS_AB / ss$MSE\n\n  # p-values\n  p_A <- 1 - pf(F_A, ss$df_A, ss$df_error)\n  p_B <- 1 - pf(F_B, ss$df_B, ss$df_error)\n  p_AB <- 1 - pf(F_AB, ss$df_AB, ss$df_error)\n\n  # ANOVA table\n  anova_table <- data.frame(\n    Source = c(factor_a_name, factor_b_name,\n               paste0(factor_a_name, \"×\", factor_b_name), \"Error\"),\n    df = c(ss$df_A, ss$df_B, ss$df_AB, ss$df_error),\n    SS = c(ss$SS_A, ss$SS_B, ss$SS_AB, ss$SSE),\n    MS = c(MS_A, MS_B, MS_AB, ss$MSE),\n    F = c(F_A, F_B, F_AB, NA),\n    p_value = c(p_A, p_B, p_AB, NA)\n  )\n\n  # Effect sizes\n  eta_p_sq_A <- ss$SS_A / (ss$SS_A + ss$SSE)\n  eta_p_sq_B <- ss$SS_B / (ss$SS_B + ss$SSE)\n  eta_p_sq_AB <- ss$SS_AB / (ss$SS_AB + ss$SSE)\n\n  omega_sq_A <- max(0, (ss$SS_A - ss$df_A * ss$MSE) / (ss$SST + ss$MSE))\n  omega_sq_B <- max(0, (ss$SS_B - ss$df_B * ss$MSE) / (ss$SST + ss$MSE))\n  omega_sq_AB <- max(0, (ss$SS_AB - ss$df_AB * ss$MSE) / (ss$SST + ss$MSE))\n\n  effect_sizes <- data.frame(\n    Effect = c(factor_a_name, factor_b_name,\n               paste0(factor_a_name, \"×\", factor_b_name)),\n    partial_eta_sq = c(eta_p_sq_A, eta_p_sq_B, eta_p_sq_AB),\n    omega_sq = c(omega_sq_A, omega_sq_B, omega_sq_AB)\n  )\n\n  # Return results\n  result <- list(\n    anova_table = anova_table,\n    effect_sizes = effect_sizes,\n    cell_means = tapply(y, list(factor_a, factor_b), mean)\n  )\n\n  class(result) <- \"my_twoway_anova\"\n  return(result)\n}\n\n# Print method\nprint.my_twoway_anova <- function(x, ...) {\n  cat(\"\\n\", rep(\"=\", 60), \"\\n\", sep = \"\")\n  cat(\"         Two-Way ANOVA Results\\n\")\n  cat(rep(\"=\", 60), \"\\n\\n\", sep = \"\")\n\n  cat(\"ANOVA Table:\\n\")\n  print(x$anova_table, digits = 4, row.names = FALSE)\n\n  cat(\"\\n\\nEffect Sizes:\\n\")\n  print(x$effect_sizes, digits = 3, row.names = FALSE)\n\n  cat(\"\\n\\nCell Means:\\n\")\n  print(round(x$cell_means, 2))\n\n  cat(\"\\n\", rep(\"=\", 60), \"\\n\", sep = \"\")\n}\n\n# Test on dairy data\nresult <- my_twoway_anova(dairy$fat_pct, dairy$breed, dairy$diet,\n                            \"Breed\", \"Diet\")\nprint(result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n============================================================\n         Two-Way ANOVA Results\n============================================================\n\nANOVA Table:\n     Source df       SS        MS       F p_value\n      Breed  1 27.89289 27.892891 20829.3       0\n       Diet  2  1.15298  0.576490   430.5       0\n Breed×Diet  2  0.48544  0.242718   181.3       0\n      Error 48  0.06428  0.001339      NA      NA\n\n\nEffect Sizes:\n     Effect partial_eta_sq omega_sq\n      Breed          0.998   0.9064\n       Diet          0.947   0.0374\n Breed×Diet          0.883   0.0157\n\n\nCell Means:\n         Balanced HighForage HighGrain\nHolstein     3.69       3.91      3.44\nJersey       5.15       5.49      4.86\n\n============================================================\n```\n\n\n:::\n\n```{.r .cell-code}\n# Verify against lm()\ncat(\"\\n\\nVerification against base R:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nVerification against base R:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(anova(lm(fat_pct ~ breed * diet, data = dairy)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: fat_pct\n           Df  Sum Sq Mean Sq   F value    Pr(>F)    \nbreed       1 27.8929 27.8929 20829.345 < 2.2e-16 ***\ndiet        2  2.7536  1.3768  1028.130 < 2.2e-16 ***\nbreed:diet  2  0.0608  0.0304    22.712 1.145e-07 ***\nResiduals  48  0.0643  0.0013                        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n✓ Results match!\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Results match!\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Custom Solver Success\n\nOur solver produces results identical to R's built-in functions, confirming we understand the underlying mathematics. This is the power of building from first principles!\n:::\n\n---\n\n# Connection to Regression Framework\n\n## ANOVA as a Special Case of Regression\n\nTwo-way ANOVA is **multiple regression with categorical predictors**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ANOVA approach\nanova_fit <- aov(fat_pct ~ breed * diet, data = dairy)\ncat(\"=== ANOVA Results ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== ANOVA Results ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(anova_fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq  F value   Pr(>F)    \nbreed        1 27.893  27.893 20829.35  < 2e-16 ***\ndiet         2  2.754   1.377  1028.13  < 2e-16 ***\nbreed:diet   2  0.061   0.030    22.71 1.15e-07 ***\nResiduals   48  0.064   0.001                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Regression approach (same model!)\nreg_fit <- lm(fat_pct ~ breed * diet, data = dairy)\ncat(\"\\n=== Regression ANOVA ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Regression ANOVA ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(anova(reg_fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: fat_pct\n           Df  Sum Sq Mean Sq   F value    Pr(>F)    \nbreed       1 27.8929 27.8929 20829.345 < 2.2e-16 ***\ndiet        2  2.7536  1.3768  1028.130 < 2.2e-16 ***\nbreed:diet  2  0.0608  0.0304    22.712 1.145e-07 ***\nResiduals  48  0.0643  0.0013                        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# R-squared\ncat(\"\\nR² =\", summary(reg_fit)$r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nR² = 0.9979111 \n```\n\n\n:::\n\n```{.r .cell-code}\n# From ANOVA components\nR_sq_anova <- 1 - ss_test$SSE / ss_test$SST\ncat(\"From ANOVA: 1 - SSE/SST =\", R_sq_anova, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFrom ANOVA: 1 - SSE/SST = 0.9979111 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ ANOVA and regression are mathematically identical\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ ANOVA and regression are mathematically identical\n```\n\n\n:::\n:::\n\n\n**The unified framework**: All linear models use $\\mathbf{y} = \\mathbf{Xβ} + \\mathbf{e}$\n\n---\n\n# Common Pitfalls and Best Practices\n\n::: {.callout-warning}\n## Top 5 Pitfalls\n\n1. **Interpreting main effects with significant interactions** – Focus on simple effects instead\n2. **Using Type I SS for unbalanced designs** – Always use Type III\n3. **Skipping interaction plots** – Plots are mandatory, not optional\n4. **Ignoring effect sizes** – Report ω² or η²ₚ alongside p-values\n5. **Assuming balance** – Check with `table()` first\n:::\n\n::: {.callout-tip}\n## Best Practices\n\n✓ Check balance before analysis\n✓ Use Type III SS for unbalanced data\n✓ Test interaction first\n✓ Create interaction plots\n✓ Check assumptions (diagnostic plots)\n✓ Report effect sizes\n✓ Conduct simple effects if interaction significant\n✓ Interpret in biological context\n:::\n\n---\n\n# Summary and Looking Ahead\n\n## Key Takeaways\n\n✓ Two-way ANOVA tests **two main effects and their interaction**\n✓ Interactions mean the effect of one factor **depends on** the other\n✓ Type III SS recommended for **unbalanced designs**\n✓ Interaction plots reveal patterns **numbers cannot show**\n✓ Effect sizes quantify **practical importance**\n✓ All fits within the **unified linear model framework**\n\n## Next Week: ANCOVA\n\nWeek 10 combines factors (from ANOVA) with continuous covariates (from regression):\n- Adjust group means for covariate effects\n- Test homogeneity of slopes\n- Increase precision by controlling for continuous variables\n\n---\n\n**Previous**: [Week 8: Contrasts and Estimable Functions](../Week08_Contrasts/Week08_Contrasts.qmd)\n\n**Next**: [Week 10: Analysis of Covariance (ANCOVA)](../Week10_ANCOVA/Week10_ANCOVA.qmd)\n\n",
    "supporting": [
      "Week09_TwoWayANOVA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}